// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GO49xIdpaeGt5wGR-Vu2UFRnFbMVsEo',
    appId: '1:787166487096:web:6d45f4b947cc727d5d3ccd',
    messagingSenderId: '787166487096',
    projectId: 'siaga-banjir-b73a8',
    authDomain: 'siaga-banjir-b73a8.firebaseapp.com',
    storageBucket: 'siaga-banjir-b73a8.firebasestorage.app',
    measurementId: 'G-SLRSBPBM0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiOXqMRENpFYPIAKKBREN-p0YiV1bHkY',
    appId: '1:787166487096:android:2858c4803b40e5db5d3ccd',
    messagingSenderId: '787166487096',
    projectId: 'siaga-banjir-b73a8',
    storageBucket: 'siaga-banjir-b73a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJnomI9JUk6RyLnGh2CzrzlgmkFWK05U',
    appId: '1:787166487096:ios:ff45fad1904788a95d3ccd',
    messagingSenderId: '787166487096',
    projectId: 'siaga-banjir-b73a8',
    storageBucket: 'siaga-banjir-b73a8.firebasestorage.app',
    iosBundleId: 'com.example.siagaBanjir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJnomI9JUk6RyLnGh2CzrzlgmkFWK05U',
    appId: '1:787166487096:ios:ff45fad1904788a95d3ccd',
    messagingSenderId: '787166487096',
    projectId: 'siaga-banjir-b73a8',
    storageBucket: 'siaga-banjir-b73a8.firebasestorage.app',
    iosBundleId: 'com.example.siagaBanjir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0GO49xIdpaeGt5wGR-Vu2UFRnFbMVsEo',
    appId: '1:787166487096:web:6f9a50889791f5955d3ccd',
    messagingSenderId: '787166487096',
    projectId: 'siaga-banjir-b73a8',
    authDomain: 'siaga-banjir-b73a8.firebaseapp.com',
    storageBucket: 'siaga-banjir-b73a8.firebasestorage.app',
    measurementId: 'G-G9R9CTPC00',
  );
}
