// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi8JPnSTu3SO2oqN5710rQBlokCWpJJsY',
    appId: '1:877759372264:web:bd96559ad4d82dff2da25d',
    messagingSenderId: '877759372264',
    projectId: 'siaga-banjir-ca823',
    authDomain: 'siaga-banjir-ca823.firebaseapp.com',
    storageBucket: 'siaga-banjir-ca823.firebasestorage.app',
    measurementId: 'G-K2PXFFZ61B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCb_LEFCLZk1S9zI0etvs4X9nHKjBJmo',
    appId: '1:877759372264:android:cfcdc45f80510ff02da25d',
    messagingSenderId: '877759372264',
    projectId: 'siaga-banjir-ca823',
    storageBucket: 'siaga-banjir-ca823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAYdynjcQGmh8PRLcPgGRagpkAPNcu6E',
    appId: '1:877759372264:ios:ddf3ba1fafe4aa122da25d',
    messagingSenderId: '877759372264',
    projectId: 'siaga-banjir-ca823',
    storageBucket: 'siaga-banjir-ca823.firebasestorage.app',
    iosBundleId: 'com.example.siagaBanjir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxAYdynjcQGmh8PRLcPgGRagpkAPNcu6E',
    appId: '1:877759372264:ios:ddf3ba1fafe4aa122da25d',
    messagingSenderId: '877759372264',
    projectId: 'siaga-banjir-ca823',
    storageBucket: 'siaga-banjir-ca823.firebasestorage.app',
    iosBundleId: 'com.example.siagaBanjir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi8JPnSTu3SO2oqN5710rQBlokCWpJJsY',
    appId: '1:877759372264:web:091efa93a33012b62da25d',
    messagingSenderId: '877759372264',
    projectId: 'siaga-banjir-ca823',
    authDomain: 'siaga-banjir-ca823.firebaseapp.com',
    storageBucket: 'siaga-banjir-ca823.firebasestorage.app',
    measurementId: 'G-JMYR78ZZXK',
  );
}
